// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
      /*throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );*/
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBSMRAdDKvRDGK8GcDBhUBN-4OH_1sV0Uc',
    appId: '1:391097048021:web:8fe42869728b086481fb5c',
    messagingSenderId: '391097048021',
    projectId: 'chatting-project-flutter-1',
    authDomain: 'chatting-project-flutter-1.firebaseapp.com',
    storageBucket: 'chatting-project-flutter-1.appspot.com',
    measurementId: 'G-9L54KZDSX3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD4Dwcm1jJBPieyF4fDx8W6Sun0VH9hzD8',
    appId: '1:391097048021:android:dd8aa6a316423dc081fb5c',
    messagingSenderId: '391097048021',
    projectId: 'chatting-project-flutter-1',
    storageBucket: 'chatting-project-flutter-1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDSEgKnQcYahBXIyStkOoetSKjeuSG7LYI',
    appId: '1:391097048021:ios:9717ff294ccfaaea81fb5c',
    messagingSenderId: '391097048021',
    projectId: 'chatting-project-flutter-1',
    storageBucket: 'chatting-project-flutter-1.appspot.com',
    iosBundleId: 'com.example.chattingAppFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDSEgKnQcYahBXIyStkOoetSKjeuSG7LYI',
    appId: '1:391097048021:ios:60fb9f9785e20f4b81fb5c',
    messagingSenderId: '391097048021',
    projectId: 'chatting-project-flutter-1',
    storageBucket: 'chatting-project-flutter-1.appspot.com',
    iosBundleId: 'com.example.chattingAppFlutter.RunnerTests',
  );
}
